title: My Super Dope Webpage
author: MonicaUnlimited
description: > # this means to ignore newlines until "baseurl:"
  Lorem Khaled Ipsum is the Greatest!

# social links
github_username:  github.com/MonicaUnlimited

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
